### ISSUE TITLE
Maximum call stack size exceeded when removing many patterns

### ISSUE THREAD

**Issue by StarpTech** [mcollina/bloomrun#57]
Hi, I faced with a `call stack size exceeded` error. If you remove some `add` calls the error does not happen.

```js
const bloomrun = require('bloomrun')()

const noop = () => 'test'

bloomrun.add({ topic: 'math', cmd: 'add1' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add2' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add3' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add4' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add5' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add6' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add7' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add8' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add9' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add10' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add11' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add12' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add13' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add14' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add15' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add16' }, noop)
bloomrun.add({ topic: 'math', cmd: 'add17' }, noop)

bloomrun.list(null, {
  patterns: true
}).forEach(function (element) {
  bloomrun.remove(element)
})

```
Error
```
E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:30
Bucket.prototype.remove = function (pattern, payload) {
                                   ^

RangeError: Maximum call stack size exceeded
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:30:36)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)
    at Bucket.remove (E:\Repositorys\hemera\node_modules\bloomrun\lib\bucket.js:41:14)

```
- **NodeJs:** v8.1.2
- **OS:** Windows 10

**Comment by mcollina** [comment]
It might be a while before I can have a look (vacations and all that). If you want to have a look..

**Comment by StarpTech** [comment]
Of course, I will have a look.

**Comment by StarpTech** [comment]
@mcollina I create a PR

**Comment by DonovanBoddy** [comment]
This error still exists in v4.1.1 and can be reproduced with the following code

```
const bloomrun = require('bloomrun')()
const noop = () => 'test'
for (let index = 0; index < 5000; index++) {
    bloomrun.add({ topic: 'math', cmd: `add${index}` }, noop)
}
bloomrun.list(null, {
    patterns: true
}).forEach(function (element) {
    bloomrun.remove(element)
})
```

Error - 
```
D:\Workspace\Node.js\DummyServer\node_modules\bloomrun\lib\bucket.js:29
Bucket.prototype.remove = function (pattern, payload) {
                                   ^

RangeError: Maximum call stack size exceeded

```
